### ISSUE TITLE
Cannot import State of the Union dataset without the 'django-extensions' Python module, which is listed as optional in requirements.txt

### ISSUE THREAD

**Issue by cojoco** [BYU-NLP-Lab/topicalguide#67]
Whenever attempting to run <Topical Guide>/default_datasets/import_state_of_the_union.sh, it gives the following error (along with 2 more like it):

```
Traceback (most recent call last):
  File "tg.py", line 452, in <module>
    main()
  File "tg.py", line 446, in main
    execute[args.which](args)
  File "tg.py", line 88, in exec_import_dataset
    database_id = import_system_utilities.run_syncdb(database_info)
  File "/aml/home/cojoco/git/topicalguide/import_tool/import_system_utilities.py", line 91, in run_syncdb
    django.setup()
  File "/usr/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named django_extensions
```

If this truly is required, it needs to be moved from 'optional'. If it's not required, then we need to make sure importing the State of the Union dataset doesn't fail if you don't have it installed.

**Comment by cojoco** [comment]
I removed 'django_extensions' from under the 'INSTALLED_APPS' section in the settings.py file, and the error went away. It looks like it was trying to use 'django_extensions' every time it created a django server, and was throwing the above error when it couldn't find it.

**Comment by cojoco** [comment]
I tested this by cloning BYU-NLP-Lab/topicalguide/dev into a completely clean directory and then removing 'django.extensions' from under "INSTALLED_APPS". The import of the dataset worked (after using the solution for #69 as well), and the server appeared to start and run successfully. If we use django-extensions elsewhere, then we will need to move it from the 'optional' section to the main section of the requirements.txt. I am closing this issue for now.
