### ISSUE TITLE
Cannot import State of the Union dataset with Django 1.7

### ISSUE THREAD

**Issue by cojoco** [BYU-NLP-Lab/topicalguide#69]
If I attempt to import the State of the Union dataset, it fails with the following traceback:
```
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "tg.py", line 452, in <module>
    main()
  File "tg.py", line 446, in main
    execute[args.which](args)
  File "tg.py", line 88, in exec_import_dataset
    database_id = import_system_utilities.run_syncdb(database_info)
  File "/local/cojoco/git/topicalguide/import_tool/import_system_utilities.py", line 98, in run_syncdb
    call_command('migrate', database=dataset_identifier)
  File "/local/cojoco/git/topicalguide/venvTestReqs/lib/python2.7/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/local/cojoco/git/topicalguide/venvTestReqs/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/local/cojoco/git/topicalguide/venvTestReqs/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 164, in handle
    emit_post_migrate_signal(created_models, self.verbosity, self.interactive, connection.alias)
  File "/local/cojoco/git/topicalguide/venvTestReqs/lib/python2.7/site-packages/django/core/management/sql.py", line 268, in emit_post_migrate_signal
    using=db)
  File "/local/cojoco/git/topicalguide/venvTestReqs/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/local/cojoco/git/topicalguide/venvTestReqs/lib/python2.7/site-packages/django/contrib/auth/management/__init__.py", line 83, in create_permissions
    ctype = ContentType.objects.db_manager(using).get_for_model(klass)
  File "/local/cojoco/git/topicalguide/venvTestReqs/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 51, in get_for_model
    defaults={'name': smart_text(opts.verbose_name_raw)},
  File "/local/cojoco/git/topicalguide/venvTestReqs/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/local/cojoco/git/topicalguide/venvTestReqs/lib/python2.7/site-packages/django/db/models/query.py", line 422, in get_or_create
    return self.get(**lookup), False
  File "/local/cojoco/git/topicalguide/venvTestReqs/lib/python2.7/site-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/local/cojoco/git/topicalguide/venvTestReqs/lib/python2.7/site-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/local/cojoco/git/topicalguide/venvTestReqs/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/local/cojoco/git/topicalguide/venvTestReqs/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/local/cojoco/git/topicalguide/venvTestReqs/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/local/cojoco/git/topicalguide/venvTestReqs/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/local/cojoco/git/topicalguide/venvTestReqs/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/local/cojoco/git/topicalguide/venvTestReqs/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/local/cojoco/git/topicalguide/venvTestReqs/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/local/cojoco/git/topicalguide/venvTestReqs/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/local/cojoco/git/topicalguide/venvTestReqs/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 485, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: django_content_type.name
```

**Comment by cojoco** [comment]
I have found that if I update Django (currently it updates to version 1.8.4), then the import works correctly.

**Comment by cojoco** [comment]
I cloned the repo from BYU-NLP-Lab/topicalguide/dev into a completely clean directory on my machine, and found that importing the State of the Union dataset worked if Django was updated from 1.7 to 1.8.4. This appears to be the solution to this issue, unless it breaks something else I'm not seeing.
