### ISSUE TITLE
Exception thrown during installation of dependencies

### ISSUE THREAD

**Issue by madisonjbrooks12** [BYU-NLP-Lab/topicalguide#78]
During step 2, an exception was thrown. This is the text:
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 307, in run
    strip_file_prefix=options.strip_file_prefix)
  File "/usr/lib/python2.7/site-packages/pip/req.py", line 1436, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/lib/python2.7/site-packages/pip/req.py", line 598, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/lib/python2.7/site-packages/pip/req.py", line 1841, in remove
    renames(path, new_path)
  File "/usr/lib/python2.7/site-packages/pip/util.py", line 296, in renames
    shutil.move(old, new)
  File "/usr/lib64/python2.7/shutil.py", line 303, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg-info'

Storing debug log for failure in /aml/home/mjnuss/.pip/pip.log

**Comment by madisonjbrooks12** [comment]
How I was told to fix this:

Before installing the dependencies, I typed

virtualenv ENV

inside the topicalguide directory. I then activated the environment:

source ENV/bin/activate

**Comment by nOkuda** [comment]
Perhaps it would be helpful to point users to `virtualenv` or `pyenv` in the instructions and/or make it explicit that superuser permission is necessary to install the Topical Guide as shown in the current instructions.

**Comment by madisonjbrooks12** [comment]
Sure. I can go ahead and change the instructions? And excuse my ignorance, but how does creating a virtual environment give someone superuser permissions?

**Comment by nOkuda** [comment]
You are welcome to make changes in your own fork and then make a pull request to the project (Jeff knows a lot about this).

Sorry for the confusion.  The virtual environment doesn't give a user superuser permissions.  It circumvents the need for superuser permissions for the case described in this issue.

**Comment by madisonjbrooks12** [comment]
Thanks! Makes sense.

**Comment by juanpaco** [comment]
Just to throw a monkeywrench where there was already a solution, I've been enjoying virtualenvwrapper more than directly using virtualenv.  The commands for working with it are slightly nicer for about 0 additional overhead.

And thank for you making additions to the docs!
